console.log('Launching backend index.ts!');
import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import githubRoutes from './api/github'; 
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.get('/health', (req, res) => res.send({ status: 'ok' }));
app.use('/api/github', githubRoutes); 
const PORT = process.env.PORT || 3001;
app.listen(PORT, () => console.log(`API running at http://localhost:${PORT}`));
